name: integrate

on:
  pull_request:
    branches:
      - master
      - release-*


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha  }}
        path: go/src/github.com/${{ github.repository  }}

    - name: Build the docker-compose stack
      run: ./docker/up.sh --daemon

    - name: Check running containers
      run: docker ps

    # - name: Run test suite
    #   run: docker exec backend pytest --skip-auth
